### ISSUE TITLE
骨架屏加载效果

### ISSUE THREAD

**Issue by wangxiaohang** [wangxiaohang/summary#20]
```css
.loading {
  background: -webkit-gradient(linear,left top,right top,color-stop(25%,#f2f2f2),color-stop(37%,#e6e6e6),color-stop(63%,#f2f2f2));
  background: linear-gradient(90deg,#f2f2f2 25%,#e6e6e6 37%,#f2f2f2 63%);
  background-size: 400% 100%;

  -webkit-animation: ant-skeleton-loading 1.4s ease infinite;
  animation: ant-skeleton-loading 1.4s ease infinite;
}


@-webkit-keyframes ant-skeleton-loading {
  0% {
    background-position:100% 50%
  }
  100% {
    background-position:0 50%
  }
}
@keyframes ant-skeleton-loading { 
  0% { 
    background-position:100% 50%
  }
  100% { 
    background-position:0 50%
  }
}
```
